### ISSUE TITLE
请问这个测试方法还有效吗

### ISSUE THREAD

**Issue by caoyebo** [TomAPU/checkburp#1]
您好，这个仓库启发良多。 但是我今天测试的时候，发现浏览器默认http1.1的情况下好像也已经变成轮换端口的模式了， 不知道这个检测方法是否还有效果呢？

**Comment by TomAPU** [comment]
我刚刚在Windows10的Chrome 102.0.5005.115版本上测试，发现端口依然不变。
请问你用的是什么样的浏览器

**Comment by caoyebo** [comment]
谢谢您的回复！ 我后来又测试了一下 发现是flask的问题 不知道为什么自动在response里加了connection close.  把这个去掉之后就正常了， 谢谢！
